In [1]:
import numpy as np
import gc
import timeit
import torch 

# Concat large arrays 

In [2]:
real_shape = (206928225, 100)
testshape = (int(206928225/100), 100)
testshape
test = True
no_tries = 3

In [3]:
if test:
    shape = testshape
else:
    shape = real_shape

In [4]:
def fast_concat(se,pe,oe):
    
    assert se.shape == pe.shape, "Error! fast_concat with differing shapes"
    assert se.shape == oe.shape, "Error! fast_concat with differing shapes"
       
    x = np.empty((se.shape[0],se.shape[1]*3),dtype=np.float32)
    x[:,0:100] =se
    x[:,100:200] = pe
    x[:,200:] = oe
    
    return x

def insert_row_into_array_np(arr,row,col_ix):
    col = np.repeat(row,len(arr)).reshape((len(arr),col_ix[1]-col_ix[0]))
    arr[:,col_ix[0]:col_ix[1]] = col
    return arr

def insert_row_into_array_zero_np(arr,row,col_ix):
    col = np.repeat(row,len(arr)).reshape((len(arr),col_ix[1]-col_ix[0]))
    arr[:,col_ix[0]:col_ix[1]] = 0
    arr[:,col_ix[0]:col_ix[1]] += col
    
    return arr

def insert_row_into_array_loop_np(arr,row,col_ix):
    for i in range(len(arr)):
        arr[:,col_ix[0]:col_ix[1]][i] = row
    return arr

def insert_row_into_array_loop_zero_np(arr,row,col_ix):
    arr[:,col_ix[0]:col_ix[1]] = 0
    for i in range(len(arr)):
        arr[:,col_ix[0]:col_ix[1]][i] += row
    return arr

In [5]:
def insert_row_into_array_torch(arr,row,col_ix):
    col = row.repeat(len(arr),1)
    arr[:,col_ix[0]:col_ix[1]] = col
    return arr

def insert_row_into_array_zero_torch(arr,row,col_ix):
    col = row.repeat(len(arr),1)
    arr[:,col_ix[0]:col_ix[1]] = 0
    arr[:,col_ix[0]:col_ix[1]] += col
    return arr

def insert_row_into_array_loop_torch(arr,row,col_ix):
    for i in range(len(arr)):
        arr[:,col_ix[0]:col_ix[1]][i] = row
    return arr

def insert_row_into_array_loop_zero_torch(arr,row,col_ix):
    arr[:,col_ix[0]:col_ix[1]] = 0
    for i in range(len(arr)):
        arr[:,col_ix[0]:col_ix[1]][i] += row
    return arr

In [6]:
testrow = np.zeros(shape[1])
testarray = np.empty((shape[0],shape[1]*3))

try_np = f"insert_row_into_array_np(testarray,testrow,(100,200));gc.collect()"
try_np_zero= f"insert_row_into_array_zero_np(testarray,testrow,(100,200));gc.collect()"
try_np_loop= f"insert_row_into_array_loop_np(testarray,testrow,(100,200));gc.collect()"
try_np_loop_zero = f"insert_row_into_array_loop_zero_np(testarray,testrow,(100,200));gc.collect()"

## Time numpy functions

In [7]:
timeit.timeit(try_np, number=no_tries,globals=globals())

KeyboardInterrupt: 

In [ ]:
timeit.timeit(try_np_zero, number=no_tries,globals=globals())

In [ ]:
timeit.timeit(try_np_loop, number=no_tries,globals=globals())

In [ ]:
timeit.timeit(try_np_loop_zero, number=no_tries,globals=globals())

## Try torch functions

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
testrow = torch.tensor(testrow).to(device)
testarray = torch.tensor(testarray).to(device)

try_torch = f"insert_row_into_array_torch(testarray,testrow,(100,200));gc.collect()"
try_torch_zero= f"insert_row_into_array_zero_torch(testarray,testrow,(100,200));gc.collect()"
try_torch_loop= f"insert_row_into_array_loop_torch(testarray,testrow,(100,200));gc.collect()"
try_torch_loop_zero= f"insert_row_into_array_loop_zero_torch(testarray,testrow,(100,200));gc.collect()"

In [ ]:
timeit.timeit(try_torch, number=no_tries,globals=globals())

In [ ]:
timeit.timeit(try_torch_zero, number=no_tries,globals=globals())

In [ ]:
timeit.timeit(try_torch_loop, number=no_tries,globals=globals())

In [ ]:
timeit.timeit(try_torch_loop_zero, number=no_tries,globals=globals())

In [ ]:
# pytorch model
import torchmetrics
import torch
from torch import nn 


class ClassifierSimple(torch.nn.Module):
    def __init__(self,input_dim=300,hidden_size=64):
        super(ClassifierSimple, self).__init__()
        
        
        self.layers = nn.Sequential(
                # flatten input if necessary
                nn.Flatten(),
                nn.Linear(input_dim,hidden_size),
                nn.ReLU(),
                nn.Linear(hidden_size,1)
        )
        
        self.output_activation = nn.Sigmoid()
                
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
 
        
    
    def forward(self,x):        
        
        return self.layers(x)
    def predict(self,x):
        x.to(self.device)
        
        return self.output_activation(self.layers(x))
    def predict_numpy(self,x):
        x = torch.tensor(x)
        x.to(self.device)
        return self.output_activation(self.layers(x)).detach().cpu().numpy()
        
    


# Test Prediction function

In [ ]:
model = ClassifierSimple()
model = model.to(device)

In [ ]:
test = torch.empty((shape[0],shape[1]*3)).to(device)

In [ ]:
timeit.timeit(f"model(test);gc.collect()", number=10,globals=globals())

In [ ]:
timeit.timeit(f"model.predict_numpy(test);gc.collect()", number=10,globals=globals())

No Difference on cpu ... need to check on gpu

In [1]:
import torch

In [2]:
x = torch.zeros(10000,300)

In [3]:
row = torch.ones(100).reshape(1,100)

In [9]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
x[:,100:200].index_fill(0,torch.arange(len(x)),row)

RuntimeError: index_fill_ only supports a 0-dimensional value tensor, but got tensor with 2 dimension(s).

# Test to(device)

In [104]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [13]:
import torch

In [15]:
edge_ix = [2,3,6,7]

In [14]:
x = torch.empty(10)

In [3]:
x = torch.rand(15000**2)/10

In [4]:
len(x)

225000000

In [12]:
def compute_rank(scores,ix,mask=None):
    if mask == None:    
        optimistic_rank =(scores > scores[ix]).sum()+1
        pessimistic_rank = (scores >= scores[ix]).sum()

        
    else:
        
        optimistic_rank = ((scores > scores[ix]).index_fill(0,mask,False)).sum()+1
        pessimistic_rank = ((scores >= scores[ix]).index_fill(0,mask,False)).sum()
        
    rank = (optimistic_rank+pessimistic_rank)*0.5
        
    return rank

In [6]:
def test_for_loop(no_nodes):
    for ix in range(no_nodes):
        compute_rank(x,ix)

In [31]:
from sklearn.utils.extmath import cartesian
no_entities = 10

In [32]:
s_o_combs = torch.tensor(cartesian((range(no_entities),range(no_entities))))

In [42]:
s_o_combs[s_o_combs[:,1] == 4]

tensor([[0, 4],
        [1, 4],
        [2, 4],
        [3, 4],
        [4, 4],
        [5, 4],
        [6, 4],
        [7, 4],
        [8, 4],
        [9, 4]])

In [37]:
edge = torch.tensor((8,3))

In [24]:
def get_head_ix(edge):
    return edge[1]
    

In [39]:
(s_o_combs[s_o_combs[:,0] == 8]) == edge

tensor([[ True, False],
        [ True, False],
        [ True, False],
        [ True,  True],
        [ True, False],
        [ True, False],
        [ True, False],
        [ True, False],
        [ True, False],
        [ True, False]])

In [12]:
test_for_loop()

In [9]:
import timeit
no_nodes = 2500

In [10]:
timeit.timeit(f'test_for_loop({no_nodes})', number=1,globals=globals())

KeyboardInterrupt: 

In [28]:
from scipy.stats import rankdata

In [ ]:
timeit.timeit('rankdata(x)',number=1,globals=globals())